### ISSUE TITLE
remote workspace support

### ISSUE THREAD

**Issue by rlnt** [AhmadHddad/vscode-extension-disabler#1]
I love the idea of your extension.
It's sadly not usable for me since it seems like the extension doesn't recognize remote workspaces as valid workspaces.

I have a workspace on my WSL2 machine opened and when I enter the command for the extension disabler, I get the message:
```
Please add a workspace first
```

Could you add support for remote environments?
This is the extension which makes it possible to edit remote workspaces in WSL https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

extension disabler: v0.0.3
vscode: v1.53.2
os: Windows 10 Pro, WSL2 with Ubuntu 20.04 (linux sub system)

**Comment by AhmadHddad** [comment]
Thanks for using the extension.
Currently, I am working on some new features, and as soon as release 0.1.0, I'll start working on this issue.

**Comment by AhmadHddad** [comment]
Solved
