### ISSUE TITLE
Can't apply deleted profile on any workspace

### ISSUE THREAD

**Issue by ahmadzraiq** [AhmadHddad/vscode-extension-disabler#6]
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

After deleting a profile i didn't get apply on workspace

**Comment by AhmadHddad** [comment]
Fixed in V 1.3
