### ISSUE TITLE
Workspace binding should be optional

### ISSUE THREAD

**Issue by rlnt** [AhmadHddad/vscode-extension-disabler#7]
Pretty happy with the extension so far. It makes my workflow a lot easier, thanks for that!

Right now the extension requires you to set up a workspace for your current project to register a specific extension profile for it.
I am not really using the workspace feature. Most of the time, I open a folder in VSCode as my project and then save it via Project Manager (another extension). Workspaces aren't required in this workflow.

I would really like to see overriding of this. Let's say you place a json file in the `.vscode` folder inside your project and in there you define the profile for the extension disabler so when opening up this project, the extension knows which extensions to disable without the need for a workspace.

Would that be possible?

Versions
Extension Disabler: `0.1.3`
VSCode:
```
Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by AhmadHddad** [comment]
Hey, @DAmNRelentless  Thanks for using this extension.

I will do some research on that, and I was thinking about adding it, but it's very urgent.
Currently, I have some issues regarding sqlite3 and Arm64 (Apple M1), i think i need some help with that.

**Comment by AhmadHddad** [comment]
Fixing getting Workspaces list and Workspace binding should be optional
