### ISSUE TITLE
Message each time I try to use the extension: "Please add a workspace first" / "There are no workspaces registered!"

### ISSUE THREAD

**Issue by MostHated** [AhmadHddad/vscode-extension-disabler#9]
Hello,
    I just installed this extension, as it sounds like it's close to being just what I was after, but unfortunately, I keep getting the following messages, "Please add a workspace first" as well as "There are no workspaces registered!". I definitely have a work space loaded, and in my storage.json, I have the following info. Perhaps I just don't know what "registered" means when it comes to workspaces? Also, is it 100% necessary to have to tie the extension profile to a workspace? I feel like it would be more useful to be able to simply have multiple global profiles that you can switch between at any time, but then also have a workspace setting defining a specific profile you wish to automatically utilize. I don't often use workspaces in the first place as I use an extension called "Project Manager" to select and switch projects.

<details>
<summary>Warning/Errors</summary>

![](https://i.imgur.com/kqD3JIq.png)

</details>

I saw you had asked others for info from the storage.json file, here is what I found for the particular workspace I was trying to use.
<details>
<summary>storage.json entry</summary>

```json

"openedWindows": [
            {
                "workspaceIdentifier": {
                    "id": "1221a9317c9f1641a1f1a6f7c879c68d",
                    "configURIPath": "file:///mnt/ha/ha.code-workspace"
                },
                "backupPath": "/home/mosthated/.config/Code - Insiders/Backups/1221a9317c9f1641a1f1a6f7c879c68d",
                "uiState": {
                    "mode": 0,
                    "x": 1920,
                    "y": 27,
                    "width": 2560,
                    "height": 1053
                }
            }
]
```

</details>

Thanks,
 -MH

**Comment by AhmadHddad** [comment]
Hi @MostHated, Sorry for the late reply I was very busy in the past time.
this error is due to VsCode keeping changing its structure, I pushed a workaround for that along with a new feature, and it will be published soon.
thanks for using this extension.
